- [x] set builtin (for args)
- [x] $@
- [ ] variable substitution extensions
  - [ ] parameterize expansion using a struct instead of globals
- [ ] sourcing /etc/profile and .profile
- [ ] implement case statement
- [ ] aliases
- [ ] file globbing
- [ ] env vars for cmd exec (mklocal)
  - [ ] local variables
- [ ] 
